SchoolManagement/Controllers/InstitutionsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SchoolManagement.Models;

namespace SchoolManagement.Controllers
{
    public class InstitutionsController : Controller
    {
        private SchoolModelContainer db = new SchoolModelContainer();

        // GET: Institutions
        public ActionResult Index()
        {
            return View(db.InstitutionSet.ToList());
        }

        // GET: Institutions/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Institution institution = db.InstitutionSet.Find(id);
            if (institution == null)
            {
                return HttpNotFound();
            }
            return View(institution);
        }

        // GET: Institutions/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Institutions/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,web_address,Address,Contact_number,State,City,PostalCode")] Institution institution)
        {
            if (ModelState.IsValid)
            {
                db.InstitutionSet.Add(institution);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(institution);
        }

        // GET: Institutions/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Institution institution = db.InstitutionSet.Find(id);
            if (institution == null)
            {
                return HttpNotFound();
            }
            return View(institution);
        }

        // POST: Institutions/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,web_address,Address,Contact_number,State,City,PostalCode")] Institution institution)
        {
            if (ModelState.IsValid)
            {
                db.Entry(institution).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(institution);
        }

        // GET: Institutions/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Institution institution = db.InstitutionSet.Find(id);
            if (institution == null)
            {
                return HttpNotFound();
            }
            return View(institution);
        }

        // POST: Institutions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Institution institution = db.InstitutionSet.Find(id);
            db.InstitutionSet.Remove(institution);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SchoolManagement/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>@ViewBag.Title - My ASP.NET MVC Application</title>
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")
    </head>

    <body>
        <div class="container-fluid">
            <div class="container">
                <div class="row" style="height:20px"></div>
                <div class="row">
                    <div id="main">
                        <header>

                            <nav class="navbar navbar-inverse navbar-fixed-top custumnav">

                                <div class="navbar-header">
                                    <button type="button" class="navbar-toggle" data-target="#myNavbar" data-toggle="collapse">
                                        <span class="icon-bar"></span>
                                        <span class="icon-bar"></span>
                                        <span class="icon-bar"></span>
                                    </button>

                                    <div class="float-left">
                                        <p class="site-title">@Html.ActionLink("   Digital School", "Index", "Home")</p>
                                    </div>
                                </div>
                                <div class="navbar-collapse collapse" id="myNavbar">
                                    <ul class="nav navbar-nav">
                                        <li>
                                            <a href="@Url.Action("Index", "Home")">
                                                <span class=" glyphicon glyphicon-home">Home</span>
                                            </a>
                                        </li>

                                        <li><a href="@Url.Action("About", "Home")"><span class=" glyphicon glyphicon-eye-open">About</span></a></li>
                                        <li><a href="@Url.Action("Contact", "Home")"><span class=" glyphicon  glyphicon-earphone">Contact</span></a></li>

                                    </ul>

                                    <div class="float-right">
                                        <section id="login">
                                            @Html.Partial("_LoginPartial")
                                        </section>
                                    </div>

                                </div>

                            </nav>




                            <div class="area "></div><nav class="main-menu">
                                <ul>
                                    <li>
                                        <a href="#">
                                            <i class="glyphicon glyphicon-dashboard"></i>
                                            <span class="nav-text">
                                                Dashboard
                                            </span>
                                        </a>

                                    </li>
                                    <li class="has-subnav">
                                        <a href="@Url.Action("create", "Institutions")">
                                            <i class="glyphicon glyphicon-education"></i>
                                            <span class="nav-text">
                                                Institute
                                            </span>
                                        </a>

                                    </li>
                                    <li class="has-subnav">
                                        <a href="#">
                                            <i class="glyphicon glyphicon-briefcase"></i>
                                            <span class="nav-text">
                                                Departments
                                            </span>
                                        </a>

                                    </li>
                                    <li class="has-subnav">
                                        <a href="#">
                                            <i class="glyphicon glyphicon-tag"></i>
                                            <span class="nav-text">
                                                Students
                                            </span>
                                        </a>

                                    </li>
                                    <li>
                                        <a href="#">
                                            <i class="glyphicon glyphicon-user"></i>
                                            <span class="nav-text">
                                                Staff
                                            </span>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            <i class="glyphicon glyphicon-usd"></i>
                                            <span class="nav-text">
                                                Fee
                                            </span>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            <i class="glyphicon glyphicon-certificate"></i>
                                            <span class="nav-text">
                                                Examination
                                            </span>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            <i class="glyphicon glyphicon-tasks"></i>
                                            <span class="nav-text">
                                                Events
                                            </span>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            <i class="glyphicon glyphicon-envelope"></i>
                                            <span class="nav-text">
                                                Mailbox
                                            </span>
                                        </a>
                                    </li>
                                </ul>

                                <ul>
                                    <li>
                                        <a href="#">
                                            <i class=" glyphicon glyphicon-wrench"></i>
                                            <span class="nav-text">
                                                Setting
                                            </span>
                                        </a>
                                    </li>
                                </ul>
                            </nav>
                        </header>

                        <div id="body">
                            @RenderSection("featured", required: false)
                            <section class="content-wrapper main-content clear-fix">
                                @RenderBody()
                            </section>
                        </div>

                        <footer>
                            <div class="content-wrapper">
                                <div class="float-left">
                                    <p>&copy; @DateTime.Now.Year - My ASP.NET MVC Application</p>
                                </div>
                            </div>
                        </footer>

                        @Scripts.Render("~/bundles/jquery")
                        @RenderSection("scripts", required: false)
                    </div>
                </div>
            </div>
        </div>
    </body>
</html>
<style type="text/css">
    .navbar-fixed-top
    {
        position:relative;
    }
    .custumnav {
        height: 60px;
    }

        .custumnav a {
            font-size:large;
            font-family: Candara;
            color: white;
        }

        .custumnav li {
            font-size: large;
            font-family: Candara;
            color: white;
            text-decoration: none;
        }

            .custumnav li a {
                text-decoration: none;
            }
            .custumnav li:active {
                background-color: grey;
            }

            .custumnav li:hover {
                background-color: #00CED1;
            }
 


.fa-2x {
font-size: 2em;
}
.glyphicon {
position: relative;
display: table-cell;
width: 30px;
height: 30px;
text-align: center;
vertical-align: middle;
font-size:20px;
}
    .nav-text {
        font-size :medium;
    }

.main-menu:hover,nav.main-menu.expanded {
width:250px;
overflow:visible;
}

.main-menu {
background:black;
border-right:1px solid #e5e5e5;
border-radius:50px/15px;
box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
position:absolute;
top:100px;
bottom:0;
height:auto;
left:0;
width:30px;
overflow:hidden;
-webkit-transition:width .05s linear;
transition:width .05s linear;
-webkit-transform:translateZ(0) scale(1,1);
 background: -webkit-linear-gradient(left,Black,#4d4d33);
z-index:1000;

}

.main-menu>ul {
margin:7px 0;
}

.main-menu li {
position:relative;
display:block;
width:250px;
}

.main-menu li>a {
position:relative;
display:table;
border-collapse:collapse;
border-spacing:0;
color:#999;
 font-family: arial;
font-size: 14px;
text-decoration:none;
-webkit-transform:translateZ(0) scale(1,1);
-webkit-transition:all .1s linear;
transition:all .1s linear;
  
}

.main-menu .nav-icon {
position:relative;
display:table-cell;
width:60px;
height:36px;
text-align:center;
vertical-align:middle;
font-size:18px;
}

.main-menu .nav-text {
position:relative;
display:table-cell;
vertical-align:middle;
width:190px;
  font-family: 'Titillium Web', sans-serif;
}

.main-menu>ul.logout {
position:absolute;
left:0;
bottom:0;
}

.no-touch .scrollable.hover {
overflow-y:hidden;
}

.no-touch .scrollable.hover:hover {
overflow-y:auto;
overflow:visible;
}

a:hover,a:focus {
text-decoration:none;
}

nav {
-webkit-user-select:none;
-moz-user-select:none;
-ms-user-select:none;
-o-user-select:none;
user-select:none;
}

nav ul,nav li {
outline:0;
margin:0;
padding:0;
}
.main-menu li:hover>a,nav.main-menu li.active>a,.dropdown-menu>li>a:hover,.dropdown-menu>li>a:focus,.dropdown-menu>.active>a,.dropdown-menu>.active>a:hover,.dropdown-menu>.active>a:focus,.no-touch .dashboard-page nav.dashboard-menu ul li:hover a,.dashboard-page nav.dashboard-menu ul li.active a {
color:#fff;
background-color:#00CED1;
}
.area {
float: left;
background: #e2e2e2;
width: 100%;
height: 100%;
}


</style>